IMAGES= arrowdown.imgbin \
arrowleft.imgbin \
arrowright.imgbin \
arrowup.imgbin \
cmd_alpha.imgbin \
cmd_beta.imgbin \
cmd_bondadd.imgbin \
cmd_bondsub.imgbin \
cmd_d.imgbin \
cmd_ff.imgbin \
cmd_gd.imgbin \
cmd_g.imgbin \
cmd_omega.imgbin \
cmd_psi.imgbin \
cmd_start.imgbin \
cursor_topleft.imgbin \
cursor_topright_botleft.imgbin \
cursor_botright.imgbin \
element_Be.imgbin \
element_B.imgbin \
element_C.imgbin \
element_F.imgbin \
element_He.imgbin \
element_H.imgbin \
element_Li.imgbin \
element_Ne.imgbin \
element_N.imgbin \
element_O.imgbin \
fringebot.imgbin \
fringeleft.imgbin \
fringeright.imgbin \
fringetop.imgbin \
linebotleft.imgbin \
linebotright.imgbin \
lineh.imgbin \
linetopleft.imgbin \
linetopright.imgbin \
linev.imgbin \
loopdown.imgbin \
loopleft.imgbin \
loopright.imgbin \
loopup.imgbin \
grid0.imgbin \
grid1.imgbin \
grid2.imgbin \
grid3.imgbin \
grid_edge_bot.imgbin \
grid_edge_right.imgbin \
sensor0.imgbin \
sensor1.imgbin \
sensor2.imgbin \
sensor3.imgbin

